### ISSUE TITLE
New visualization chapter

### ISSUE THREAD

**Issue by antagomir** [microbiome/OMA#133]
Add a new chapter on visualization, showing a compact set of common techniques, with links to other chapters.

Also link to multi-panel plot packages:
-    [ggpubr](https://rpkgs.datanovia.com/ggpubr/)
-    cowplot
-    gridExtra
-    patchwork

And the [ggplot2-book](https://ggplot2-book.org/arranging-plots.html).

**Comment by RiboRings** [comment]
Hi! Should we maybe make a list of items to cover and decide how to structure the chapter?

**Comment by antagomir** [comment]
I would start with a brief set of references to the above-mentioned resources.

This chapter could be useful but it is also problematic because there will be overlap with many other chapters.

@TuomasBorman do you have a suggestion on what should be included in such chapter?

**Comment by TuomasBorman** [comment]
You could check plots that we already have. I think this kind of chapter is useful because many times I have ended up searching certain tricks. Sometimes it took long to find them and sometimes I didn't even find them. 

In my opinion, this section could include useful visualization tricks that did not fit to other chapters. 

So, it could include sections for

1. Boxplot
2. Heatmap
3. How to combine multiple plots
4. ...

Especially, [Composition heatmap section](https://microbiome.github.io/OMA/microbiome-community.html#composition-heatmap) is quite unclear because of those different heatmaps which still include same information.

However, I think that it would be useful to include those in our book, because e.g. I did not find how to create complex heatmaps using only ggplot. 

So, I suggest that only one heatmap example is left to Composition heatmap section and others are moved into Visualization chapter

**Comment by antagomir** [comment]
Ok good. So there would additional subchapters focusing on specific visualization techniques like the ones mentioned above.

Sounds feasible. But it will be important to avoid duplication of material that is easily available from other independent tutorials. Where possible, we should instead identify one or more of the best available external sources, and link to them for more ideas. This way the information can be found through OMA but we can save potentially a lot of maintenance effort. When more customized approaches are needed for OMA, and not readily available elsewhere, then it is well justified to add new material to OMA for those.

**Comment by RiboRings** [comment]
#147 is the corresponding pull request. I had to close it for now because it uses 1 hour of GitHub Actions running time every new push and the run fails (I'm not sure why).
