### ISSUE TITLE
Improve pdf version

### ISSUE THREAD

**Issue by TuomasBorman** [microbiome/OMA#143]
Hi,

the book is now available also in pdf format (PR: https://github.com/microbiome/OMA/pull/142). However, it includes some issues. For example, page 14 includes figure that does not fit into page. Also code chunks are not scaled properly, and in multiple cases the whole code cannot be seen as it does not fit into page. 

These fixes should be done. I don't know but there might be some kind of option to scale code chunks. Otherwise we should add line breaks manually, I think.

-Tuomas

**Comment by antagomir** [comment]
Maintaining parallel copies of HTML and PDF where everything is optimized for both is something pretty hard to maintain in the long run. I think we either need to find an automated solution, not provide PDF, or accept that PDF is not rendered optimally (but then the shortcomings should not be major, otherwise it is better to just not share pdf). I am not sure at this point which of these would be the most feasible. In general, this kind of gitbooks do not provide PDFs although sometimes they do.

**Comment by TuomasBorman** [comment]
Yep. I think we should focus on html version. pdf is nice to have, and I think it is OK after those changes are merged
