### ISSUE TITLE
Failing data downloads

### ISSUE THREAD

**Issue by antagomir** [microbiome/OMA#182]
Problem: Automated examples that use online data from microbiomeDataSets (or curatedMetagenomicData) are often failing in Github Actions. Perhaps due to temporary network issues. This is so frequent that it is a bottleneck for book builds.

Proposed action: 
- in OMA examples, switch to using only data sets that are readily available in R packages
- considering adding some of the current online data sets into the R packages as well

**Comment by TuomasBorman** [comment]
Or, as we use only HintikkaData from the microbiomeDataSets and because we do not have multo-omics data in other R packages(?), --> 

1. Save HintikkaData as MAE object in OMA
2. Show but do not run chunks that download the data from web
3. Run but do not show chunks that load the object from OMA
4. considering adding some of the current online data sets into the R packages as well

**Comment by antagomir** [comment]
HintikkaXOData is now available in mia;

`data(HintikkaXOData, package="mia")`

-> Check that the examples that use HintikkaXOData in OMA would use that (and not the download from microbiomeDataSets).

This might have been implemented already but has to be checked, then closed.
