### ISSUE TITLE
most abundant taxa - function error

### ISSUE THREAD

**Issue by li-fangyeo** [microbiome/OMA#315]
Hi,

I was wondering how do I get this function to work? I've already updated R and all the packages to the latest version.
<img width="522" alt="image" src="https://github.com/microbiome/OMA/assets/95231403/70fdd60a-0527-4fa6-ae63-9031ac21d418">

<img width="488" alt="image" src="https://github.com/microbiome/OMA/assets/95231403/70ad0d65-7d09-408c-aafe-bf0caf8a7b8d">

**Comment by antagomir** [comment]
Does the error occur on the second function call (lapply..)?

**Comment by li-fangyeo** [comment]
Okay. I found two things - 1) the tutorial produces an error for both datasets, unless changed to transformCounts. 2)lapply(rowData) works for my data but lapply(colData()) doesn't.

1. If i follow the code you attached above, it works both the demo data and my data.
2. If I follow the tutorial, there is an error with transformAssay, which I circumvented with transformCounts
<img width="537" alt="image" src="https://github.com/microbiome/OMA/assets/95231403/03d11ba2-16df-43f6-a5b3-8a08f583b0f5">
3. Continuing with GP data, the tutorial code works fine.
4. Continuing with my data (x1), the tutorial code doesn't work 
<img width="571" alt="image" src="https://github.com/microbiome/OMA/assets/95231403/c5c99d34-da9f-403e-9a23-e78b38d8c936">
5. But, if i add the altExps (x1 )<- splitByRanks(x1), i can get ma
<img width="539" alt="image" src="https://github.com/microbiome/OMA/assets/95231403/3c038670-5671-4f4b-9eb1-824945d45930">
6. The tutorial code still doesn't work for my data (Something is different in my data from GP). The difference is in lapply(rowData()) and lapply(colData())
<img width="514" alt="image" src="https://github.com/microbiome/OMA/assets/95231403/8695ead9-f5b5-464a-a5c0-02e51abfb9ae">

**Comment by TuomasBorman** [comment]
2. Is `transformAssay`  from the `mia` package or from other package? (Just checking. It looks like you might have attached some package that overrides the function.)

4. Run `colData(x1)$dominant_taxa[ lengths(colData(x1)$dominant_taxa) > 1 ]` --> it seems that there is a tie --> multiple dominant taxa

**Comment by antagomir** [comment]
btw as a side note, you can write shorter, like `x1$dominant_taxa` instead of `colData(x1)$dominant_taxa`. These do the same thing.

**Comment by li-fangyeo** [comment]
2. "transformAssay from the mia package" I'm not sure. 

<img width="477" alt="image" src="https://github.com/microbiome/OMA/assets/95231403/3ebfa825-3e53-4ae4-aec3-639435ad22f5">

4. You are right! I read your comment about ties, somewhere. 
<img width="326" alt="image" src="https://github.com/microbiome/OMA/assets/95231403/16ac2bf3-2bd3-461e-bb7e-d1c59faf2300">

I managed to get a graph showing two dominant taxa, although I'm not entirely sure if what I'm generating is correct. 

<img width="671" alt="image" src="https://github.com/microbiome/OMA/assets/95231403/edc2d222-8d02-4e45-80f2-b004b0ab6a31">

**Comment by TuomasBorman** [comment]
2 It seems that you have not the latest version of mia. The transformAssay functions has been added just lately

4 You want to create an ordination plot where you color samples based on their most dominant taxa? --> The most dominant taxon for each sample is determined:

1) Calculate the most abundant taxa across samples.
2) Calculate the most dominant taxon in each sample.
3) Determine whether the most dominant taxon in a sample is also the most abundant taxon across samples.


I think the better solution might be (as Leo already mentioned):

1. Show all dominant taxa.
2. Agglomerate data based on prevalence. Taxa under threshold --> Other


Something like this
```

tse <- agglomerateByPrevalence()
tse <- addPerSampleDominanFeature()
tse <- runMDS()
plotReducedDim(colour_by = "dominant_taxa")
```

**Comment by antagomir** [comment]
Thanks Tuomas for a clear example.

@li-fangyeo try to load the latest development version of mia:
`devtools::install_github("microbiome/mia")`

then restart R and load it in fresh session:
`library(mia)`

to make sure you use right package, try:
`mia::transformAssay` instead of just `transformAssay`.

Some remarks on your point 4.. : 

- you detected one case where a particular sample (SD0735) has two equally abundant dominant taxa (Pseudomonas and Siphoviridae); 
- `addPerSampleDominantFeatures` and `getTopTaxa` do different things; your code seems to mix these and I am not sure what the end goal is. If you want to show dominant taxa per each sample, then use `addPerSampleDominantFeatures`, if you want to summarize data based on globally most top taxa (by mean, median, prevalence.. of your choice) then you can identify them with `getTopTaxa` and then merge; however I think an easier way would be to just merge rare taxa with `agglomerateByPrevalence`

It would be easier to help if you would copypaste code as text, rather than images (that cannot be copypasted).
