### ISSUE TITLE
Errors encountered when following the OMA DA example

### ISSUE THREAD

**Issue by RachBioHaz** [microbiome/OMA#319]
Hi,
I'm trying to follow the differential abundance example (Ch 11) in the OMA,  but I'm encountering multiple errors along the way. Is there an updated book or DA walkthrough available? It seems functions have changed and identifying the alternatives and correct syntax to use has been problematic.

Cheers

**Comment by antagomir** [comment]
Thanks - we will look into this asap.

**Comment by antagomir** [comment]
May I ask if you had some particular DA method/s in mind specifically, could help to debug. OMA should be synced with the latest package versions, we need to see what causes this.

**Comment by RachBioHaz** [comment]
I am going to use ALDEx2, MaAsLin2 and ANCOM-BC2 for DA testing. I was just working my way through the OMA tutorial and I encountered changes to functions/ function names in the book. I was not able to correctly identify which mia functions to use when looking at Git logs and the Reference page of functions. Based on all the changes happening in mia, I suspect it's just a matter of updating the book to reflect the new function names/syntax. I'm still relatively new to bioinformatics and it just became confusing trying to identify what to use in lieu of what was in the book.

**Comment by antagomir** [comment]
Right. I think it is now the other way round; we recently updated some function names. You could try to upgrade the packages in R with:

```
devtools::install_github("microbiome/mia")
devtools::install_github("microbiome/miaViz")
devtools::install_github("FrederickHuangLin/ANCOMBC")
```

I would expect that this will help. 

It would be good to know which package versions you are using. The `sessionInfo()` command should tell this.

We are checking if we would switch back to the old names in OMA in order to allow some more time for various users to gradually upgrade their packages.

**Comment by ake123** [comment]
The above installation commands should solve the problem

**Comment by TuomasBorman** [comment]
I believe this is solved.
