### ISSUE TITLE
Bug in DMM?

### ISSUE THREAD

**Issue by antagomir** [microbiome/OMA#338]
In the DMM clustering example in Chapter 10.4 we have:

```
# Run the model and calculates the most likely number of clusters from 1 to 7
tse_dmm <- cluster(tse, name = "DMM", DmmParam(k = 1:7, type = "laplace"), 
                   MARGIN = "samples", full = TRUE)
```

I belive we should have instead:

```
# Run the model and calculates the most likely number of clusters from 1 to 7
tse_dmm <- cluster(tse, name = "DMM", BLUSPARAM=DmmParam(k = 1:7, type = "laplace"), 
                   MARGIN = "samples", full = TRUE)
```

-> Check and fix as necessary, also from rest of the chapter.

Are you willing to have a look, @BananaCancer ?

**Comment by BananaCancer** [comment]
The `BLUSPARAM` parameter is mandatory since there isn't a default value. Therefore, simply putting `DmmParam` works fine and I think is easy enough to understand (like in the [bluster vignettes](https://bioconductor.org/packages/release/bioc/vignettes/bluster/inst/doc/clusterRows.html)).
I could still fix if you think that's relevant, but the tutorials & doc explain how to use the function and omitting `BLUSPARAM` parameter makes it easier to read in my opinion.

**Comment by antagomir** [comment]
Ok. I might have had outdated version of mia or bluster, I got error from the first one but not any more after some updates and testing.
