### ISSUE TITLE
Correcting link for datasets 

### ISSUE THREAD

**Issue by ake123** [microbiome/OMA#468]
- Replace Hintikka link with https://microbiome.github.io/mia/reference/HintikkaXOData.html and add Tengeler link as https://microbiome.github.io/mia/reference/Tengeler2020.html (see chapter 2 for examplle)

-  explain the other mia datasets along with Hintikka and Tengeler which are found. we don't want to replicate info that is already elsewhere but instead in OMA just mention where to find data & its documentation [Link to data & its documentation](https://microbiome.github.io/mia/reference/index.html#datasets)
- and also do the same correspondingly for miaViz, miaTime

**Comment by antagomir** [comment]
For point one, instead of linking to individual data sets, just cite as follows:

Let's not explain the individual data sets. We don't want to replicate info that is already elsewhere but instead in OMA just mention where to find data & its documentation.

R packages contain additional demonstration data sets (see the Datasets section of the reference page):
- [mia reference](https://microbiome.github.io/mia/reference/index.html)
- [miaViz reference](https://microbiome.github.io/miaViz/reference/index.html)
- [miaTime reference](https://microbiome.github.io/miaTime/reference/index.html)
